---
- name: CI Scenario - Network
  hosts: targets
  become: true
  pre_tasks:
    - name: Ensure network discovery variables are present
      ansible.builtin.assert:
        that:
          - ci_primary_iface | default('') | length > 0
          - ci_primary_ipv4_cidr | default('') | length > 0
          - ci_primary_gateway | default('') | length > 0
  vars:
    bootstrap_user: "netadmin"
    bootstrap_ssh_enabled: false
    bootstrap_hostname_enabled: true
    bootstrap_hostname: "network-test-server"
    bootstrap_firewall_enabled: false
    bootstrap_network_enabled: true
    bootstrap_network_interface: "{{ ci_primary_iface }}"
    bootstrap_network_connection: "bootstrap-{{ ci_primary_iface }}"
    bootstrap_static_ip: "{{ ci_primary_ipv4_cidr }}"
    bootstrap_gateway: "{{ ci_primary_gateway }}"
    bootstrap_dns4_ignore_auto: false
    bootstrap_ipv6_disabled: true
    bootstrap_expand_fs_enabled: false
    bootstrap_reboot_enabled: false
  roles:
    - bootstrap
