---
- name: Verify CI Scenario - Network
  hosts: targets
  become: true
  gather_facts: true
  tasks:
    - name: Ensure no bootstrap NetworkManager netplan renderer file is created
      ansible.builtin.stat:
        path: /etc/netplan/99-networkmanager.yaml
      register: bootstrap_nm_renderer
      failed_when: bootstrap_nm_renderer.stat.exists
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure no bootstrap NetworkManager managed snippet is created
      ansible.builtin.stat:
        path: /etc/NetworkManager/conf.d/10-bootstrap-managed.conf
      register: bootstrap_nm_managed
      failed_when: bootstrap_nm_managed.stat.exists
      when: ansible_facts['distribution'] == 'Debian'

    - name: Verify active interface can be detected via default route
      ansible.builtin.command:
        cmd: ip route show default
      register: default_route
      changed_when: false
      failed_when: default_route.stdout | trim | length == 0

    - name: Verify firewalld service is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
      check_mode: true
      register: firewalld_check
      failed_when: firewalld_check.changed

    - name: Verify ssh service is allowed in firewall
      ansible.builtin.command:
        cmd: firewall-cmd --zone=public --list-services
      register: firewall_services
      changed_when: false
      failed_when: "'ssh' not in firewall_services.stdout.split()"
