---
- name: Verify Full Configuration
  hosts: all
  become: true
  gather_facts: true
  vars:
    ssh_key_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/.ssh_keys"
  tasks:
    - name: Check if running in container
      ansible.builtin.stat:
        path: /.dockerenv
      register: _dockerenv

    # User verification
    - name: Verify user exists
      ansible.builtin.user:
        name: fulladmin
        state: present
      check_mode: true
      register: user_check
      failed_when: user_check.changed

    - name: Verify custom group was created
      ansible.builtin.group:
        name: operators
        state: present
      check_mode: true
      register: group_check
      failed_when: group_check.changed

    - name: Verify user is in custom group
      ansible.builtin.shell: |
        groups fulladmin | grep operators
      register: custom_group_check
      changed_when: false
      failed_when: custom_group_check.rc != 0

    - name: Verify user is in extra group
      ansible.builtin.shell: |
        groups fulladmin | grep adm
      register: extra_group_check
      changed_when: false
      failed_when: extra_group_check.rc != 0

    # SSH key verification
    - name: Get inventory hostname
      ansible.builtin.set_fact:
        test_hostname: "{{ inventory_hostname }}"

    - name: Check if private key was generated
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519"
      delegate_to: localhost
      become: false
      register: private_key

    - name: Fail if key not generated
      ansible.builtin.fail:
        msg: "SSH key was not generated"
      when: not private_key.stat.exists

    # SSH hardening verification
    - name: Verify SSH port changed to 2222
      ansible.builtin.shell: |
        grep -E '^Port 2222' /etc/ssh/sshd_config
      register: ssh_port
      changed_when: false
      failed_when: ssh_port.rc != 0

    - name: Verify SSH password auth disabled
      ansible.builtin.shell: |
        grep -E '^PasswordAuthentication no' /etc/ssh/sshd_config
      register: ssh_password
      changed_when: false
      failed_when: ssh_password.rc != 0

    # Hostname verification (skip in container)
    - name: Verify hostname (skip in container)
      ansible.builtin.debug:
        msg: "Hostname verification skipped in container"
      when: _dockerenv.stat.exists

    # Firewall verification (skip in container)
    - name: Verify firewalld is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
      check_mode: true
      register: firewalld_check
      failed_when: firewalld_check.changed
      when: not _dockerenv.stat.exists

    - name: Verify custom port 8080 is allowed
      ansible.builtin.shell: |
        firewall-cmd --list-ports | grep 8080/tcp
      register: port_8080
      changed_when: false
      failed_when: port_8080.rc != 0
      when: not _dockerenv.stat.exists

    - name: Verify custom port 8443 is allowed
      ansible.builtin.shell: |
        firewall-cmd --list-ports | grep 8443/tcp
      register: port_8443
      changed_when: false
      failed_when: port_8443.rc != 0
      when: not _dockerenv.stat.exists

    - name: Verify custom zone testzone exists
      ansible.builtin.shell: |
        firewall-cmd --get-zones | grep testzone
      register: custom_zone
      changed_when: false
      failed_when: custom_zone.rc != 0
      when: not _dockerenv.stat.exists

    - name: Verify port 9999 is allowed in testzone
      ansible.builtin.shell: |
        firewall-cmd --zone=testzone --list-ports | grep 9999/tcp
      register: zone_port
      changed_when: false
      failed_when: zone_port.rc != 0
      when: not _dockerenv.stat.exists

    - name: Skip firewall verification in container
      ansible.builtin.debug:
        msg: "Firewall verification skipped in container"
      when: _dockerenv.stat.exists

    # Network verification (skip in container - requires real VM)
    - name: Skip network verification in container
      ansible.builtin.debug:
        msg: "Network configuration skipped in container (requires real VM)"
      when: _dockerenv.stat.exists

    - name: Print verification summary
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "FULL CONFIG - PASSED"
          - "===================================="
          - "User: fulladmin"
          - "Custom group: operators (created)"
          - "Extra groups: adm"
          - "SSH key: generated (ed25519)"
          - "SSH port: 2222"
          - "SSH password auth: disabled"
          - "Hostname: skipped (container)"
          - "Firewall ports: skipped (container)"
          - "Firewall custom zones: skipped (container)"
          - "Network: skipped (container)"
          - "===================================="

- name: Cleanup generated keys
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove generated test keys
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/.ssh_keys"
        state: absent
