---
- name: Verify CI Scenario - Network
  hosts: targets
  become: true
  gather_facts: true
  tasks:
    - name: Verify NetworkManager is running
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
      check_mode: true
      register: nm_service
      failed_when: nm_service.changed

    - name: Verify network connection exists
      ansible.builtin.command:
        cmd: nmcli -g connection.id connection show "bootstrap-{{ ci_primary_iface }}"
      register: nm_connection
      changed_when: false
      failed_when: nm_connection.stdout | trim != "bootstrap-{{ ci_primary_iface }}"

    - name: Verify IPv4 method is manual
      ansible.builtin.command:
        cmd: nmcli -g ipv4.method connection show "bootstrap-{{ ci_primary_iface }}"
      register: ipv4_method
      changed_when: false
      failed_when: ipv4_method.stdout | trim != "manual"

    - name: Verify configured IPv4 address is present
      ansible.builtin.command:
        cmd: nmcli -g ipv4.addresses connection show "bootstrap-{{ ci_primary_iface }}"
      register: ipv4_addresses
      changed_when: false
      failed_when: ci_primary_ipv4_cidr not in ipv4_addresses.stdout

    - name: Verify IPv6 is disabled
      ansible.builtin.command:
        cmd: nmcli -g ipv6.method connection show "bootstrap-{{ ci_primary_iface }}"
      register: ipv6_method
      changed_when: false
      failed_when: ipv6_method.stdout | trim != "disabled"
