---
- name: Verify CI Scenario - Network
  hosts: targets
  become: true
  gather_facts: true
  tasks:
    - name: Verify NetworkManager is running
      ansible.builtin.systemd:
        name: NetworkManager
        state: started
      check_mode: true
      register: nm_service
      failed_when: nm_service.changed

    - name: Verify active NetworkManager connection exists
      ansible.builtin.command:
        cmd: nmcli -t -f NAME,DEVICE con show --active
      register: nm_active_connections
      changed_when: false
      failed_when: (nm_active_connections.stdout_lines | default([]) | length) == 0

    - name: Check NetworkManager netplan renderer file
      ansible.builtin.stat:
        path: /etc/netplan/99-networkmanager.yaml
      register: netplan_nm_renderer_file

    - name: Verify netplan renderer is set to NetworkManager on Ubuntu
      ansible.builtin.command:
        cmd: grep -E '^\\s*renderer:\\s*NetworkManager$' /etc/netplan/99-networkmanager.yaml
      changed_when: false
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
        - netplan_nm_renderer_file.stat.exists

    - name: Verify Debian NetworkManager ifupdown managed config exists
      ansible.builtin.command:
        cmd: grep -E '^\\s*managed\\s*=\\s*true$' /etc/NetworkManager/conf.d/10-bootstrap-managed.conf
      changed_when: false
      when: ansible_facts['distribution'] == 'Debian'

    - name: Verify firewalld service is running
      ansible.builtin.systemd:
        name: firewalld
        state: started
      check_mode: true
      register: firewalld_check
      failed_when: firewalld_check.changed

    - name: Verify ssh service is allowed in firewall
      ansible.builtin.command:
        cmd: firewall-cmd --zone=public --list-services
      register: firewall_services
      changed_when: false
      failed_when: "'ssh' not in firewall_services.stdout.split()"
