---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: bootstrap-${MOLECULE_DISTRO:-debian13}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  config_options:
    defaults:
      deprecation_warnings: false
      result_format: yaml
  inventory:
    host_vars:
      bootstrap-${MOLECULE_DISTRO:-debian13}:
        ansible_user: root
        bootstrap_hostname: "test-server"

verifier:
  name: ansible

scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
