---
- name: Converge - SSH Key Generation
  hosts: all
  become: true
  vars:
    # User configuration
    bootstrap_user: "sshtest"

    # SSH key generation
    bootstrap_ssh_pubkey: ""
    bootstrap_ssh_key_generate: true
    bootstrap_ssh_key_local_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/.ssh_keys"
    bootstrap_ssh_key_type: "ed25519"
    bootstrap_ssh_key_exclusive: false

    # Disable other features - focus on key generation
    bootstrap_ssh_enabled: false
    bootstrap_hostname_enabled: false
    bootstrap_firewall_enabled: false
    bootstrap_network_enabled: false
    bootstrap_expand_fs_enabled: false
    bootstrap_reboot_enabled: false

  roles:
    - bootstrap
