---
- name: Verify SSH Key Generation
  hosts: all
  become: true
  gather_facts: true
  vars:
    ssh_key_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/.ssh_keys"
  tasks:
    - name: Verify user exists
      ansible.builtin.user:
        name: sshtest
        state: present
      check_mode: true
      register: user_check
      failed_when: user_check.changed

    - name: Get inventory hostname
      ansible.builtin.set_fact:
        test_hostname: "{{ inventory_hostname }}"

    - name: Check if private key was generated locally
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519"
      delegate_to: localhost
      become: false
      register: private_key

    - name: Check if public key was generated locally
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519.pub"
      delegate_to: localhost
      become: false
      register: public_key

    - name: Fail if keys not generated
      ansible.builtin.fail:
        msg: "SSH keys were not generated in {{ ssh_key_dir }}"
      when: not private_key.stat.exists or not public_key.stat.exists

    - name: Read generated public key
      ansible.builtin.slurp:
        src: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519.pub"
      delegate_to: localhost
      become: false
      register: pubkey_content

    - name: Verify public key is in authorized_keys
      ansible.builtin.shell: |
        grep "{{ (pubkey_content.content | b64decode).split()[1] }}" /home/sshtest/.ssh/authorized_keys
      register: auth_keys_check
      changed_when: false
      failed_when: auth_keys_check.rc != 0

    - name: Verify private key permissions
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519"
      delegate_to: localhost
      become: false
      register: private_key_perms

    - name: Check private key permissions are correct
      ansible.builtin.assert:
        that:
          - private_key_perms.stat.mode == '0600'
        fail_msg: "Private key permissions should be 0600, got {{ private_key_perms.stat.mode }}"

    - name: Print verification summary
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "SSH KEY GENERATION - PASSED"
          - "===================================="
          - "User: sshtest"
          - "Key type: ed25519"
          - "Private key: {{ ssh_key_dir }}/{{ test_hostname }}_ed25519"
          - "Public key: {{ ssh_key_dir }}/{{ test_hostname }}_ed25519.pub"
          - "Permissions: {{ private_key_perms.stat.mode }}"
          - "Deployed to authorized_keys: YES"
          - "===================================="

- name: Cleanup generated keys
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove generated test keys
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/.ssh_keys"
        state: absent
