---
- name: Verify CI Scenario - SSH Key Generation
  hosts: targets
  become: true
  gather_facts: true
  vars:
    ssh_key_dir: "{{ lookup('env', 'CI_PROJECT_DIR') }}/.ci_ssh_keys"
  tasks:
    - name: Get inventory hostname
      ansible.builtin.set_fact:
        test_hostname: "{{ inventory_hostname }}"

    - name: Verify user exists
      ansible.builtin.user:
        name: sshtest
        state: present
      check_mode: true
      register: user_check
      failed_when: user_check.changed

    - name: Check private key exists locally
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519"
      delegate_to: localhost
      become: false
      register: private_key

    - name: Check public key exists locally
      ansible.builtin.stat:
        path: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519.pub"
      delegate_to: localhost
      become: false
      register: public_key

    - name: Fail if keys were not generated
      ansible.builtin.fail:
        msg: "Expected SSH keys in {{ ssh_key_dir }}"
      when: not private_key.stat.exists or not public_key.stat.exists

    - name: Read generated public key
      ansible.builtin.slurp:
        src: "{{ ssh_key_dir }}/{{ test_hostname }}_ed25519.pub"
      delegate_to: localhost
      become: false
      register: pubkey_content

    - name: Verify key is present in authorized_keys
      ansible.builtin.command:
        cmd: grep "{{ (pubkey_content.content | b64decode).split()[1] }}" /home/sshtest/.ssh/authorized_keys
      changed_when: false
