---
- name: Verify Minimal Configuration
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Verify user exists
      ansible.builtin.user:
        name: minimaluser
        state: present
      check_mode: true
      register: user_check
      failed_when: user_check.changed

    - name: Verify user is in correct group
      ansible.builtin.shell: |
        groups minimaluser | grep -E '(sudo|wheel)'
      register: groups_check
      changed_when: false
      failed_when: groups_check.rc != 0

    - name: Verify sudoers file does NOT exist (nopasswd_sudo disabled)
      ansible.builtin.stat:
        path: /etc/sudoers.d/minimaluser
      register: sudoers_file
      failed_when: sudoers_file.stat.exists

    - name: Verify SSH config was NOT modified (password auth still enabled)
      ansible.builtin.shell: |
        grep -E '^PasswordAuthentication no' /etc/ssh/sshd_config
      register: ssh_password
      changed_when: false
      failed_when: ssh_password.rc == 0  # Should NOT find this line

    - name: Print verification summary
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "MINIMAL CONFIG - PASSED"
          - "===================================="
          - "User: minimaluser (created)"
          - "Groups: {{ groups_check.stdout }}"
          - "Sudoers nopasswd: SKIPPED (as expected)"
          - "SSH hardening: SKIPPED (as expected)"
          - "Firewall: SKIPPED (as expected)"
          - "Hostname: SKIPPED (as expected)"
          - "===================================="
